### ISSUE TITLE
Crash when placing vanilla slab on aether legacy slab

### ISSUE THREAD

**Issue by supersaiyansubtlety** [CJMinecraft01/DoubleSlabs#4]
My game crashed when placing a sandstone slab on top of an aether legacy skyroot slab (log below). 
I've also noticed only half-compatibility with Tinker's Construct slabs: Tinker's slabs can be bottoms of double slabs but not tops (specifically, I couldn't put two different Tinker's slabs in a double slab and I couldn't put a Tinker's slab on top of a vanilla slab)

Forge 1.12.2 - 14.23.5.2847
DoubleSlabs-1.12-0.1.0
Aether Legacy - 1.4.4
Tinker's Construct - 2.12.0.157

[doubleslab-crash.txt](https://pastebin.com/TLYGn7kA)

**Comment by CJMinecraft01** [comment]
Sorry for the delay. The bug should be fixed in the latest version

**Comment by supersaiyansubtlety** [comment]
Still getting a crash under the same conditions with version 0.1.1
[new crash log](https://pastebin.com/KFhctdc2)

**Comment by CJMinecraft01** [comment]
This should now (hopefully :D) be fixed in the latest version
