### ISSUE TITLE
Can't place slabs next to each other without first completing the block

### ISSUE THREAD

**Issue by scottwilson0308** [CJMinecraft01/DoubleSlabs#8]
Hey there! First off, thanks for your time and effort that's gone into the mod :)

I've just started using the mod and when I try to place oak slabs one beside another by right clicking the side of a slab while holding another (building a 1/2 block floor), I end up placing the slab above/below the one I've clicked on.. Is it not possible to place slabs using the sides of other slabs while this mod is installed, or am I missing something? I've gone through the in-game controls, checked my configs and tried shift+right-clicking on the slabs.. no luck.

**Comment by Syndaryl** [comment]
I'm having the same issue, when you're making a slab floor, it's enough to drive you bonkers.

This is a really cool mod idea, and I'm very reluctant to give it up because of this quirk, so right now I'm doing a lot of stuff with scaffolding to work around it. I'd rather it Just Worked though ;)

**Comment by Syndaryl** [comment]
I believe Vanilla uses raytracing to determine at what angle you're clicking on the block to decide if you need to put a slab on the side or make a doubleslab or whatever. You could look into this?

**Comment by CJMinecraft01** [comment]
Sorry for the delay, I'm looking into this issue and suspect it is something to do with how I ported the 1.12 version to 1.14 (assuming this is on the 1.14 version). What I suspect is, as you can place slabs on top of a slab by clicking on the side of the block, I have accidentally forgot to check whether you intend to place it on the side of the block or the top. I'll try to get this fixed as soon as possible, again sorry for the delay

**Comment by CJMinecraft01** [comment]
This should now be fixed in the latest version, if you have any more issues, be sure to let me know!

**Comment by WenXin20** [comment]
I found out this can still happen if the upper half of a slab is right-clicked to placed another slab above. It'll instead make the block below into a double slab.
